### ISSUE TITLE
Entrez issue

### ISSUE THREAD

**Issue by jrjhealey** [happykhan/journalbot#4]
```
>>> handle = Entrez.esearch(db="pubmed", term="Alikhan NF", field="author", retmode="xml", retmax=10)
>>> record = Entrez.read(handle)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 376, in read
    record = handler.read(handle)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 205, in read
    self.parser.ParseFile(handle)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/Bio/Entrez/Parser.py", line 513, in externalEntityRefHandler
    self.dtd_urls.append(url)
UnboundLocalError: local variable 'url' referenced before assignment
```

Might be the cause of the bot failing now? Not sure why the `url` variable is listed as absent because `handle.url` returns:

```
>>> handle.url
'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?term=Alikhan+NF&retmax=10&retmode=xml&tool=biopython&db=pubmed&field=author&email=gibsongroupbot%40gmail.com'
```

**Comment by jrjhealey** [comment]
Scratch that. Seems to just be broken on my CLIMB VM biopython install. Not sure why yet.

**Comment by jrjhealey** [comment]
Update: installed from `requirements.txt` on a new server, and where Biopython was originally working, seemingly the version in requirements.txt then breaks it.

**Comment by jrjhealey** [comment]
Not an Entrez issue afterall. PR6 resolves.

https://github.com/happykhan/journalbot/pull/6
